/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class Paging extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "offset" })
    offset?: number;
}

export class Permission extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "paging" })
    @Type(() => Paging)
    paging?: Paging;

    @SpeakeasyMetadata()
    @Expose({ name: "permissions" })
    permissions?: string[];
}
